version: "3.9"
services:
  web:
    build:
      context: ./client
    ports:
      - "5432:3000"
    expose:
      - "5432"
    depends_on:
      - api
  api:
    restart: always
    build:
      context: ./server
    ports:
      - "9003:9003"
    expose:
      - "9003"
    volumes:
      - uploads:/usr/src/app/uploads
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD

volumes:
  uploads:
